# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- public

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Mirror to Git
  displayName: 'Mirror to Git'
- task: CmdLine@2
  inputs:
    script: |
      echo clone branch
      /usr/bin/git -c http.sslVerify=true clone --mirror https://wpsw2em2h7265wmbk7t7whvekjncm7rl5i5hvfqnenmraiz42loa@dev.azure.com/Red-Cross-Austria/RCA-CoronaApp/_git/RCA-CoronaApp-AG RCA-CoronaApp-AG.git --branch public


#- task: mirror-git-repository-vsts-task@1
#  inputs:
#    sourceGitRepositoryUri: 'https://dev.azure.com/Red-Cross-Austria/RCA-CoronaApp/_git/RCA-CoronaApp-AG?version=GBpublic'
#    sourceGitRepositoryPersonalAccessToken: 'wpsw2em2h7265wmbk7t7whvekjncm7rl5i5hvfqnenmraiz42loa'
#    destinationGitRepositoryUri: 'https://github.com/austrianredcross/RCA-CoronaApp-Backend'
#    destinationGitRepositoryPersonalAccessToken: '5233bcd15e9a43be825c9e2e1209debb13b14f1b'


